version: "3.9"

services:
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - shared-network
    environment:
      MONGODB_URI: mongodb://localhost:27017/chat
      API_URI: http://localhost:8080/greenswap/public/user/token
    
  mongo:
    build: ./mongo-docker
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - shared-network

volumes:
  mongo-data:
  
networks:
  shared-network:
    external: true