name: Deploy to VPS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Multi line script on remote host
        uses: appleboy/ssh-action@master
        id: ssh
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "============================================== EXECUTING ON HOST =============================================="
            echo "============================================== START OF CLEANING =============================================="
            docker stop mongo || true
            docker stop api || true
            docker rm mongo || true
            docker rm api || true
            docker rmi chat-mongo || true
            docker rmi chat-api || true
            docker network create shared-network || true
            cd /app/repos/greenswap-chat
            rm -rf *
            mkdir backend
            cd backend
            echo ============================================== END OF CLEANING ==============================================
            echo "============================================== START OF PULL =============================================="
            git config --global user.name ${{ secrets.GIT_MAIL }}
            git config --global user.email ${{ secrets.GIT_PASSWORD }}
            git clone https://github.com/Green-Swap/chat.git
            echo "============================================== START OF BUILD =============================================="
            cd chat
            git fetch
            git pull 
            git checkout dev
            git pull 
            echo "============================================== END OF BUILD =============================================="
            echo "============================================== START OF RUN =============================================="
            docker-compose up -d
            echo "============================================== END OF RUN =============================================="
            echo "============================================== START TEST =============================================="
            sleep 30
            docker ps -a 
            echo "============================================== END TEST =============================================="
